# Online Config Subscribe
# Clash For Magisk
# Credits [fyn170](https://github.com/fyn170/conf-oc)
----
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
secret: "FyNn"
bind-address: "*"
ipv6: false
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true
dns:
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - https://dns.adguard.com/dns-query
  - https://dns-google.com/dns-query
  - tls://dns.adguard.com
  - tls://dns-google.com/
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
proxies:
proxy-providers:
  Server:
    type: http
    url: "https://raw.githubusercontent.com/fyn170/conf-oc/main/proxy_provider/server.yaml"
    path: "./proxy_provider/server.yaml"
    interval: 60
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: 18+
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: ADS
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: Chat
  type: select
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - DIRECT
  - Server
- name: Server
  type: url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Server
  url: http://www.gstatic.com/generate_204
  interval: '300'
rules:
- RULE-SET,18+,Server
- RULE-SET,Ads,ADS
- RULE-SET,Direct,DIRECT
- RULE-SET,Gaming,Server
- RULE-SET,Sosmed,Server
- RULE-SET,Stream,Server
- MATCH,GLOBAL
rule-providers:
  18+:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-oc/main/rule_provider/saru.yaml"
    path: "./rule_provider/saru.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Ads:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-oc/main/rule_provider/ads.yaml"
    path: "./rule_provider/ads.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-oc/main/rule_provider/direct.yaml"
    path: "./rule_provider/direct.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Gaming:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-oc/main/rule_provider/gaming.yaml"
    path: "./rule_provider/gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Sosmed:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-oc/main/rule_provider/sosmed.yaml"
    path: "./rule_provider/sosmed.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Stream:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-oc/main/rule_provider/stream.yaml"
    path: "./rule_provider/stream.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Zerotier:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-oc/main/rule_provider/zerotier.yaml"
    path: "./rule_provider/zerotier.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300