port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
bind-address: "*"
unified-delay: true
ipv6: false
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - 1.1.1.1
    - 8.8.8.8
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
proxy-providers:
  Server:
    type: file
    bhavior: classical
    path: "./proxy_provider/server.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
proxy-groups:
- name: 18+
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: ADS
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: Chat
  type: select
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - DIRECT
  - Server
- name: Server
  type: url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Server
  url: http://www.gstatic.com/generate_204
  interval: '300'
rules:
- RULE-SET,18+,Server
- RULE-SET,Ads,ADS
- RULE-SET,Direct,DIRECT
- RULE-SET,Gaming,Server
- RULE-SET,Sosmed,Server
- RULE-SET,Stream,Server
- RULE-SET,Zerotier,Server
- MATCH,GLOBAL
rule-providers:
  18+:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/saru.yaml"
    path: "./rule_provider/saru.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Ads:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/ads.yaml"
    path: "./rule_provider/ads.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Direct:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/direct.yaml"
    path: "./rule_provider/direct.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Gaming:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/gaming.yaml"
    path: "./rule_provider/gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Reject:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/reject.yaml"
    path: "./rule_provider/reject.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Sosmed:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/sosmed.yaml"
    path: "./rule_provider/sosmed.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Stream:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/stream.yaml"
    path: "./rule_provider/stream.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Zerotier:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/zerotier.yaml"
    path: "./rule_provider/zerotier.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
