port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
bind-address: "*"
unified-delay: true
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true
dns:
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 94.140.14.14
  - 94.140.15.15
  - https://dns.adguard-dns.com/dns-query
  - https://dns.google/dns-query
  - tls://dns.adguard-dns.com
  - tls://dns.google
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 94.140.14.14
  - 94.140.15.15
proxy-providers:
  Server:
    type: file
    path: "./proxy_provider/server.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
proxy-groups:
- name: 18+
  type: select
  proxies:
  - REJECT
  - Server
- name: Ads
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: Chat
  type: select
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - DIRECT
  - Server
- name: Server
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Server
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300
rules:
- RULE-SET,18+,18+
- RULE-SET,Ads,Ads
- RULE-SET,Banking,Server
- RULE-SET,Gaming,Server
- RULE-SET,Olshop,Server
- RULE-SET,Sosmed,Server
- RULE-SET,Stream,Server
- RULE-SET,Zerotier,Server
- MATCH,GLOBAL
rule-providers:
  18+:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/saru.yaml"
    path: "./rule_provider/saru.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Ads:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/ads.yaml"
    path: "./rule_provider/ads.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Gaming:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/gaming.yaml"
    path: "./rule_provider/gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Reject:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/reject.yaml"
    path: "./rule_provider/reject.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Sosmed:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/sosmed.yaml"
    path: "./rule_provider/sosmed.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Stream:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/stream.yaml"
    path: "./rule_provider/stream.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Zerotier:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/zerotier.yaml"
    path: "./rule_provider/zerotier.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
